/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zak
 */
public class MainFrame extends javax.swing.JFrame {
    private Password userPassword = new Password();
    private Password guessedPassword = new Password();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        CreatePasscodeJpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PasswordButton1 = new javax.swing.JButton();
        PasswordButton4 = new javax.swing.JButton();
        PasswordButton7 = new javax.swing.JButton();
        PasswordButton2 = new javax.swing.JButton();
        PasswordButton5 = new javax.swing.JButton();
        PasswordButton8 = new javax.swing.JButton();
        PasswordButton3 = new javax.swing.JButton();
        PasswordButton6 = new javax.swing.JButton();
        PasswordButton9 = new javax.swing.JButton();
        PasswordButton0 = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordCreatedJLabel = new javax.swing.JLabel();
        CompromisePasscodeJpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PasswordCrackingButton7 = new javax.swing.JButton();
        PasswordCrackingButton6 = new javax.swing.JButton();
        PasswordCrackingButton1 = new javax.swing.JButton();
        PasswordCrackingButton8 = new javax.swing.JButton();
        PasswordCrackingButton2 = new javax.swing.JButton();
        PasswordCrackingButton3 = new javax.swing.JButton();
        PasswordCrackingButton4 = new javax.swing.JButton();
        PasswordCreatedJLabel1 = new javax.swing.JLabel();
        PasswordCrackingButton0 = new javax.swing.JButton();
        PasswordCrackingButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordTextField2 = new javax.swing.JTextField();
        PasswordCrackingButton9 = new javax.swing.JButton();
        PasswordAcceptedLabel = new javax.swing.JLabel();
        CrackPasscodeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        CreatePasscodeJpanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password Cracking Test");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        PasswordButton1.setText("1");
        PasswordButton1.setAlignmentX(0.5F);
        PasswordButton1.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton1.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton1ActionPerformed(evt);
            }
        });

        PasswordButton4.setText("4");
        PasswordButton4.setAlignmentX(0.5F);
        PasswordButton4.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton4.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton4ActionPerformed(evt);
            }
        });

        PasswordButton7.setText("7");
        PasswordButton7.setAlignmentX(0.5F);
        PasswordButton7.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton7.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton7ActionPerformed(evt);
            }
        });

        PasswordButton2.setText("2");
        PasswordButton2.setAlignmentX(0.5F);
        PasswordButton2.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton2.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton2ActionPerformed(evt);
            }
        });

        PasswordButton5.setText("5");
        PasswordButton5.setAlignmentX(0.5F);
        PasswordButton5.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton5.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton5ActionPerformed(evt);
            }
        });

        PasswordButton8.setText("8");
        PasswordButton8.setAlignmentX(0.5F);
        PasswordButton8.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton8.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton8ActionPerformed(evt);
            }
        });

        PasswordButton3.setText("3");
        PasswordButton3.setAlignmentX(0.5F);
        PasswordButton3.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton3.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton3ActionPerformed(evt);
            }
        });

        PasswordButton6.setText("6");
        PasswordButton6.setAlignmentX(0.5F);
        PasswordButton6.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton6.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton6ActionPerformed(evt);
            }
        });

        PasswordButton9.setText("9");
        PasswordButton9.setAlignmentX(0.5F);
        PasswordButton9.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton9.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton9ActionPerformed(evt);
            }
        });

        PasswordButton0.setText("0");
        PasswordButton0.setAlignmentX(0.5F);
        PasswordButton0.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordButton0.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButton0ActionPerformed(evt);
            }
        });

        PasswordTextField.setFont(new java.awt.Font("Segoe UI Historic", 1, 41)); // NOI18N
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Create your 4 digit passcode");

        PasswordCreatedJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordCreatedJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CreatePasscodeJpanelLayout = new javax.swing.GroupLayout(CreatePasscodeJpanel);
        CreatePasscodeJpanel.setLayout(CreatePasscodeJpanelLayout);
        CreatePasscodeJpanelLayout.setHorizontalGroup(
            CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PasswordCreatedJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CreatePasscodeJpanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePasscodeJpanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2))
                    .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreatePasscodeJpanelLayout.createSequentialGroup()
                                .addComponent(PasswordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreatePasscodeJpanelLayout.createSequentialGroup()
                                .addComponent(PasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatePasscodeJpanelLayout.createSequentialGroup()
                            .addComponent(PasswordButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PasswordButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(PasswordButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreatePasscodeJpanelLayout.setVerticalGroup(
            CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePasscodeJpanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreatePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordCreatedJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        MainTabbedPane.addTab("Create Passcode", CreatePasscodeJpanel);

        CompromisePasscodeJpanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password Cracking Test");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        PasswordCrackingButton7.setText("7");
        PasswordCrackingButton7.setAlignmentX(0.5F);
        PasswordCrackingButton7.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton7.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton7ActionPerformed(evt);
            }
        });

        PasswordCrackingButton6.setText("6");
        PasswordCrackingButton6.setAlignmentX(0.5F);
        PasswordCrackingButton6.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton6.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton6ActionPerformed(evt);
            }
        });

        PasswordCrackingButton1.setText("1");
        PasswordCrackingButton1.setAlignmentX(0.5F);
        PasswordCrackingButton1.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton1.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton1ActionPerformed(evt);
            }
        });

        PasswordCrackingButton8.setText("8");
        PasswordCrackingButton8.setAlignmentX(0.5F);
        PasswordCrackingButton8.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton8.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton8ActionPerformed(evt);
            }
        });

        PasswordCrackingButton2.setText("2");
        PasswordCrackingButton2.setAlignmentX(0.5F);
        PasswordCrackingButton2.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton2.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton2ActionPerformed(evt);
            }
        });

        PasswordCrackingButton3.setText("3");
        PasswordCrackingButton3.setAlignmentX(0.5F);
        PasswordCrackingButton3.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton3.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton3ActionPerformed(evt);
            }
        });

        PasswordCrackingButton4.setText("4");
        PasswordCrackingButton4.setAlignmentX(0.5F);
        PasswordCrackingButton4.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton4.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton4ActionPerformed(evt);
            }
        });

        PasswordCreatedJLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordCreatedJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        PasswordCrackingButton0.setText("0");
        PasswordCrackingButton0.setAlignmentX(0.5F);
        PasswordCrackingButton0.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton0.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton0ActionPerformed(evt);
            }
        });

        PasswordCrackingButton5.setText("5");
        PasswordCrackingButton5.setAlignmentX(0.5F);
        PasswordCrackingButton5.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton5.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter your 4 digit passcode");

        PasswordTextField2.setFont(new java.awt.Font("Segoe UI Historic", 1, 41)); // NOI18N
        PasswordTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextField2ActionPerformed(evt);
            }
        });

        PasswordCrackingButton9.setText("9");
        PasswordCrackingButton9.setAlignmentX(0.5F);
        PasswordCrackingButton9.setMaximumSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton9.setPreferredSize(new java.awt.Dimension(78, 50));
        PasswordCrackingButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordCrackingButton9ActionPerformed(evt);
            }
        });

        PasswordAcceptedLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PasswordAcceptedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        CrackPasscodeButton.setText("Crack Passcode");
        CrackPasscodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrackPasscodeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CompromisePasscodeJpanelLayout = new javax.swing.GroupLayout(CompromisePasscodeJpanel);
        CompromisePasscodeJpanel.setLayout(CompromisePasscodeJpanelLayout);
        CompromisePasscodeJpanelLayout.setHorizontalGroup(
            CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordCreatedJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordAcceptedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                        .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel4))
                                    .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                                                .addComponent(PasswordCrackingButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PasswordCrackingButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PasswordCrackingButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                                                .addComponent(PasswordCrackingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PasswordCrackingButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(PasswordCrackingButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompromisePasscodeJpanelLayout.createSequentialGroup()
                                            .addComponent(PasswordCrackingButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(PasswordCrackingButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PasswordCrackingButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(PasswordCrackingButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(CrackPasscodeButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CompromisePasscodeJpanelLayout.setVerticalGroup(
            CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompromisePasscodeJpanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordCrackingButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordCrackingButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CompromisePasscodeJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordCrackingButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordCrackingButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordCrackingButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(CrackPasscodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordAcceptedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordCreatedJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        MainTabbedPane.addTab("Compromise Passcode", CompromisePasscodeJpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void PasswordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton1ActionPerformed
         if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "1");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "1");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
            
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
         
    }//GEN-LAST:event_PasswordButton1ActionPerformed

    private void PasswordButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton2ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "2");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "2");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
         
    }//GEN-LAST:event_PasswordButton2ActionPerformed

    private void PasswordButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton3ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "3");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "3");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
         
    }//GEN-LAST:event_PasswordButton3ActionPerformed

    private void PasswordButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton4ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "4");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "4");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton4ActionPerformed

    private void PasswordButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton5ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "5");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "5");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton5ActionPerformed

    private void PasswordButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton6ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "6");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "6");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton6ActionPerformed

    private void PasswordButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton7ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "7");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "7");            
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton7ActionPerformed

    private void PasswordButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton8ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "8");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "8");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton8ActionPerformed

    private void PasswordButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton9ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "9");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "9");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton9ActionPerformed

    private void PasswordButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButton0ActionPerformed
        if(userPassword.passwordLength()<3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "0");
            PasswordTextField.setText(PasswordTextField.getText() + "*     ");
         }
         else if(userPassword.passwordLength()== 3){
            String currentPasscode = userPassword.getPassword();
            userPassword.setPassword(currentPasscode + "0");
            PasswordTextField.setText(PasswordTextField.getText() + "*");
            PasswordCreatedJLabel.setText("Password has been successfully created.");
         }
         else{
             PasswordCreatedJLabel.setText("Your password has already been created.");
         }
    }//GEN-LAST:event_PasswordButton0ActionPerformed

    private void PasswordCrackingButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton2ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "2");
            PasswordTextField2.setText(PasswordTextField2.getText() + "2     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "2");
            PasswordTextField2.setText(PasswordTextField2.getText() + "2");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    }//GEN-LAST:event_PasswordCrackingButton2ActionPerformed

    private void PasswordCrackingButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton3ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "3");
            PasswordTextField2.setText(PasswordTextField2.getText() + "3     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "3");
            PasswordTextField2.setText(PasswordTextField2.getText() + "3");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton3ActionPerformed

    private void PasswordTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextField2ActionPerformed

    private void PasswordCrackingButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton1ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "1");
            PasswordTextField2.setText(PasswordTextField2.getText() + "1     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "1");
            PasswordTextField2.setText(PasswordTextField2.getText() + "1");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
                
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton1ActionPerformed

    private void PasswordCrackingButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton7ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "7");
            PasswordTextField2.setText(PasswordTextField2.getText() + "7     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "7");
            PasswordTextField2.setText(PasswordTextField2.getText() + "7");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton7ActionPerformed

    private void PasswordCrackingButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton8ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "8");
            PasswordTextField2.setText(PasswordTextField2.getText() + "8     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "8");
            PasswordTextField2.setText(PasswordTextField2.getText() + "8");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton8ActionPerformed

    private void PasswordCrackingButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton6ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "6");
            PasswordTextField2.setText(PasswordTextField2.getText() + "6     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "6");
            PasswordTextField2.setText(PasswordTextField2.getText() + "6");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton6ActionPerformed

    private void PasswordCrackingButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton9ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "9");
            PasswordTextField2.setText(PasswordTextField2.getText() + "9     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "9");
            PasswordTextField2.setText(PasswordTextField2.getText() + "9");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");                
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton9ActionPerformed

    private void PasswordCrackingButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton0ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "0");
            PasswordTextField2.setText(PasswordTextField2.getText() + "0     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "0");
            PasswordTextField2.setText(PasswordTextField2.getText() + "0");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton0ActionPerformed

    private void PasswordCrackingButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton5ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "5");
            PasswordTextField2.setText(PasswordTextField2.getText() + "5     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "5");
            PasswordTextField2.setText(PasswordTextField2.getText() + "5");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton5ActionPerformed

    private void PasswordCrackingButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordCrackingButton4ActionPerformed
        if(guessedPassword.passwordLength()<3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "4");
            PasswordTextField2.setText(PasswordTextField2.getText() + "4     ");
         }
         else if(guessedPassword.passwordLength()== 3){
            String currentPasscode = guessedPassword.getPassword();
            guessedPassword.setPassword(currentPasscode + "4");
            PasswordTextField2.setText(PasswordTextField2.getText() + "4");
            if(guessedPassword.getPassword().equals(userPassword.getPassword())){
                PasswordAcceptedLabel.setText(String.format("Password %s has been accepted",guessedPassword.getPassword()));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
            else{
                PasswordAcceptedLabel.setText(String.format("Password is incorrect"));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
            }
         }
    
    }//GEN-LAST:event_PasswordCrackingButton4ActionPerformed

    private void CrackPasscodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrackPasscodeButtonActionPerformed
        long startTime = System.currentTimeMillis();
        for(int i = 0;i<=9999;i++){
             Password passwordAttempt = new Password(String.format("%04d",i));
             if(passwordAttempt.getPassword().equals(userPassword.getPassword())){
                double totalTime = System.currentTimeMillis() - startTime;
                PasswordAcceptedLabel.setText(String.format("Password %s has been Cracked in %.2f milliseconds", passwordAttempt.getPassword(),totalTime));
                PasswordTextField2.setText("");
                guessedPassword.setPassword("");
             }
      }
    }//GEN-LAST:event_CrackPasscodeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CompromisePasscodeJpanel;
    private javax.swing.JButton CrackPasscodeButton;
    private javax.swing.JPanel CreatePasscodeJpanel;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JLabel PasswordAcceptedLabel;
    private javax.swing.JButton PasswordButton0;
    private javax.swing.JButton PasswordButton1;
    private javax.swing.JButton PasswordButton2;
    private javax.swing.JButton PasswordButton3;
    private javax.swing.JButton PasswordButton4;
    private javax.swing.JButton PasswordButton5;
    private javax.swing.JButton PasswordButton6;
    private javax.swing.JButton PasswordButton7;
    private javax.swing.JButton PasswordButton8;
    private javax.swing.JButton PasswordButton9;
    private javax.swing.JButton PasswordCrackingButton0;
    private javax.swing.JButton PasswordCrackingButton1;
    private javax.swing.JButton PasswordCrackingButton2;
    private javax.swing.JButton PasswordCrackingButton3;
    private javax.swing.JButton PasswordCrackingButton4;
    private javax.swing.JButton PasswordCrackingButton5;
    private javax.swing.JButton PasswordCrackingButton6;
    private javax.swing.JButton PasswordCrackingButton7;
    private javax.swing.JButton PasswordCrackingButton8;
    private javax.swing.JButton PasswordCrackingButton9;
    private javax.swing.JLabel PasswordCreatedJLabel;
    private javax.swing.JLabel PasswordCreatedJLabel1;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField PasswordTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
